from langchain_community.vectorstores.azuresearch import (
    FIELDS_CONTENT,
    FIELDS_ID,
    FIELDS_METADATA,
    FIELDS_CONTENT_VECTOR
)

LC_AZ_SRCH_FIELD_CONTENT_NAME = FIELDS_CONTENT
LC_AZ_SRCH_FIELD_ID_NAME = FIELDS_ID
LC_AZ_SRCH_FIELD_METADATA_NAME = FIELDS_METADATA
LC_AZ_SRCH_FIELD_CONTENT_VECTOR_NAME = FIELDS_CONTENT_VECTOR
