from .base.base_file_index_field_names import (    
   FIELD_NAME_CONTENT,
   FIELD_NAME_ID,
   FIELD_NAME_METADATA,
   FIELD_NAME_CONTENT_VECTOR,
   FIELD_NAME_TITLE,
   FIELD_NAME_URI,
   FIELD_NAME_FILE_NAME,
   FIELD_NAME_FILE_TYPE,
   FIELD_NAME_FILE_SIZE,
   FIELD_NAME_LAST_MODIFIED,
   FIELD_NAME_FILE_HASH,
   FIELD_NAME_FILE_TOPIC,
   FIELD_NAME_FILE_LANGUAGE,
   FIELD_NAME_CHUNK_TOPIC1,
   FIELD_NAME_CHUNK_TOPIC2,
   FIELD_NAME_CHUNK_TOPIC3,
   FIELD_NAME_CHUNK_IN_FILE_CTX_SUMMARY,
   FIELD_NAME_CHUNK_QUESTION1,
   FIELD_NAME_CHUNK_QUESTION2,
   FIELD_NAME_CHUNK_QUESTION3,
    FIELD_NAME_FILE_TOPIC_VECTOR,
    FIELD_NAME_CHUNK_TOPIC1_VECTOR,
    FIELD_NAME_CHUNK_TOPIC2_VECTOR,
    FIELD_NAME_CHUNK_TOPIC3_VECTOR,
    FIELD_NAME_CHUNK_IN_FILE_CTX_SUMMARY_VECTOR,
    FIELD_NAME_CHUNK_QUESTION1_VECTOR,
    FIELD_NAME_CHUNK_QUESTION2_VECTOR,
    FIELD_NAME_CHUNK_QUESTION3_VECTOR
)


FIELD_NAME_THREAD_ID = "thread_id"
FIELD_NAME_USER_ID = "user_id"
